### ISSUE TITLE
[BUG] Only 'chicken chicken chicken chicken chicken chicken' text is generated

### ISSUE THREAD

**Issue by Kingki19** [Jumitti/chicken_AI#1]
Why? Do you have some tutorial how to use this? Do i need to use papers from Zotera?

**Comment by Jumitti** [comment]
@Kingki19 Hello, your problem seems very strange... can you explain your process to me?

[Can you try on this version ?](https://github.com/Jumitti/chicken_AI/blob/main/LICENCE)

**Comment by Kingki19** [comment]
here is the initial condition: 
![Screenshot (1)](https://github.com/Jumitti/chicken_AI/assets/114461022/21752da5-0bbe-47f9-b4ff-a22b11ed2efc)

and i get this result:
https://r.sine.com/chicken

OR
![Screenshot (2)](https://github.com/Jumitti/chicken_AI/assets/114461022/d5da48d3-1f54-4b48-bfca-b9533876ef1f)
[chicken.pdf](https://github.com/Jumitti/chicken_AI/files/14176522/chicken.pdf)

Can you explain this? I don't use any paper

**Comment by Kingki19** [comment]
here is the initial condition: 
![Screenshot (1)](https://github.com/Jumitti/chicken_AI/assets/114461022/21752da5-0bbe-47f9-b4ff-a22b11ed2efc)

and i get this result:
https://r.sine.com/chicken

OR
![Screenshot (2)](https://github.com/Jumitti/chicken_AI/assets/114461022/d5da48d3-1f54-4b48-bfca-b9533876ef1f)
[chicken.pdf](https://github.com/Jumitti/chicken_AI/files/14176522/chicken.pdf)

Can you explain this? I don't use any paper

**Comment by Jumitti** [comment]
I'm sorry, you need to read carefully this [FILE](https://github.com/Jumitti/chicken_AI/blob/main/LICENCE). All information you required is in.

**Comment by Kingki19** [comment]
LMAO 🤣

**Comment by Kingki19** [comment]
You made the whole app without using any model, i just realize it. 🤣

**Comment by Jumitti** [comment]
Keep the secret 🐔
