### ISSUE TITLE
LOL

### ISSUE THREAD

**Issue by cgage1** [Jumitti/chicken_AI#3]
Since I can't tell for certain if this is a joke or not, ill post this here... The output of the AI generator is a PDF where every single word is "chicken" . Im attaching the PDF that was outputted after I entered a basic prompt. 

This gave me a good laugh... however I am not sure the streamlit gallery is a good place for this application. 

[chicken.pdf](https://github.com/Jumitti/chicken_AI/files/15087290/chicken.pdf)

**Comment by Jumitti** [comment]
Hello @cgage1 :)

I'm glad you found the joke funny ;) but sometimes [LICENSE](https://github.com/Jumitti/chicken_AI/blob/main/LICENCE) gives a lot of clues ;)

But I agree with you on the Streamlit gallery. You should already know that the gallery will soon change. For the moment the gallery is updated manually, but soon this will no longer be the case (if you have a Streamlit account, you can already have access to the new gallery which updates automatically). When I requested to put my apps on the gallery, I asked in "fun". You will find the conversation attached.

Let's keep it secret ;) I'm closing your issue

Best,
Julien

[RE_ How to be in Streamlit Gallery - Streamlit.pdf](https://github.com/Jumitti/chicken_AI/files/15090117/RE_.How.to.be.in.Streamlit.Gallery.-.Streamlit.pdf)
